# Generated by Django 5.1.6 on 2025-02-23 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timeframe', models.CharField(max_length=50)),
                ('active_users', models.IntegerField()),
                ('total_patients', models.IntegerField()),
                ('critical_alerts', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('device_utilization', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('uptime', models.FloatField()),
                ('connectivity_quality', models.FloatField()),
                ('connectivity_disconnections', models.IntegerField()),
                ('battery_avg_level', models.FloatField()),
                ('battery_charge_cycles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='reports.analyticsdata')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('invalid', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='reports.devicereport')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(max_length=255)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='reports.devicereport')),
            ],
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Custom', 'Custom')], default='Daily', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('heart_rate_avg', models.FloatField()),
                ('heart_rate_min', models.FloatField()),
                ('heart_rate_max', models.FloatField()),
                ('heart_rate_out_of_range', models.IntegerField()),
                ('systolic_avg', models.FloatField()),
                ('diastolic_avg', models.FloatField()),
                ('blood_pressure_out_of_range', models.IntegerField()),
                ('temperature_avg', models.FloatField()),
                ('temperature_out_of_range', models.IntegerField()),
                ('blood_oxygen_avg', models.FloatField()),
                ('blood_oxygen_out_of_range', models.IntegerField()),
                ('total_steps', models.IntegerField()),
                ('active_minutes', models.IntegerField()),
                ('resting_hours', models.FloatField()),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='reports.healthreport')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('outcome', models.TextField()),
                ('technician', models.CharField(max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='reports.devicereport')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationAdherence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('adherence', models.FloatField()),
                ('missed', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='reports.healthreport')),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=255)),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='reports.analyticsdata')),
            ],
        ),
        migrations.CreateModel(
            name='TrendDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='reports.trend')),
            ],
        ),
    ]
