# Generated by Django 5.1.6 on 2025-02-23 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='My System', max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('language', models.CharField(default='en', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=50)),
                ('time_format', models.CharField(default='HH:mm', max_length=50)),
                ('session_timeout', models.IntegerField(default=30)),
                ('password_min_length', models.IntegerField(default=8)),
                ('password_require_numbers', models.BooleanField(default=True)),
                ('password_require_symbols', models.BooleanField(default=False)),
                ('password_require_uppercase', models.BooleanField(default=True)),
                ('password_expiry_days', models.IntegerField(default=90)),
                ('two_factor_required', models.BooleanField(default=False)),
                ('two_factor_methods', models.JSONField(default=list)),
                ('ip_whitelist', models.JSONField(default=list)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('alert_throttling_enabled', models.BooleanField(default=True)),
                ('alert_max_per_hour', models.IntegerField(default=10)),
                ('alert_cooldown_minutes', models.IntegerField(default=5)),
                ('backup_schedule', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('backup_retention', models.IntegerField(default=30)),
                ('auto_update', models.BooleanField(default=True)),
                ('maintenance_day', models.IntegerField(default=0)),
                ('maintenance_start_time', models.TimeField(default='02:00')),
                ('maintenance_duration', models.IntegerField(default=60)),
                ('integrations_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('system_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='settings.systemsettings')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('dashboard_layout', models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable'), ('detailed', 'Detailed')], default='comfortable', max_length=15)),
                ('dashboard_default_view', models.CharField(choices=[('patients', 'Patients'), ('devices', 'Devices'), ('alerts', 'Alerts')], default='patients', max_length=10)),
                ('dashboard_refresh_interval', models.IntegerField(default=30)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('do_not_disturb_enabled', models.BooleanField(default=False)),
                ('do_not_disturb_start', models.TimeField(blank=True, null=True)),
                ('do_not_disturb_end', models.TimeField(blank=True, null=True)),
                ('exclude_emergency_alerts', models.BooleanField(default=True)),
                ('high_contrast', models.BooleanField(default=False)),
                ('large_text', models.BooleanField(default=False)),
                ('reduce_motion', models.BooleanField(default=False)),
                ('screen_reader', models.BooleanField(default=False)),
                ('share_analytics', models.BooleanField(default=True)),
                ('share_location', models.BooleanField(default=False)),
                ('activity_tracking', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('events', models.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('system_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='settings.systemsettings')),
            ],
        ),
    ]
