# Generated by Django 5.1.6 on 2025-02-22 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Emergency', 'Emergency'), ('Warning', 'Warning'), ('Info', 'Info')], max_length=10)),
                ('category', models.CharField(choices=[('Health', 'Health'), ('Device', 'Device'), ('System', 'System'), ('Security', 'Security')], max_length=10)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Acknowledged', 'Acknowledged'), ('Resolved', 'Resolved')], default='Active', max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_type', models.CharField(choices=[('Device', 'Device'), ('System', 'System'), ('User', 'User')], max_length=10)),
                ('source_id', models.UUIDField()),
                ('source_name', models.CharField(max_length=255)),
                ('target_type', models.CharField(choices=[('Patient', 'Patient'), ('Device', 'Device'), ('System', 'System')], max_length=10)),
                ('target_id', models.UUIDField()),
                ('target_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('acknowledgement_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_notes', models.TextField(blank=True, null=True)),
                ('resolution_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_action', models.TextField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('acknowledgement_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolution_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('metric', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('>', '>'), ('<', '<'), ('>=', '>='), ('<=', '<='), ('=', '='), ('!=', '!=')], max_length=2)),
                ('value', models.FloatField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('actions', models.JSONField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_alert_rules', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Push', 'Push')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('target', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'type')},
            },
        ),
    ]
