# Generated by Django 5.1.6 on 2025-02-21 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('steps', models.IntegerField(default=0)),
                ('active_minutes', models.IntegerField(default=0)),
                ('heart_rate_zone_minutes', models.IntegerField(default=0)),
                ('calories_burned', models.FloatField(default=0.0)),
                ('distance_walked', models.FloatField(default=0.0)),
                ('sleep_hours', models.FloatField(default=0.0)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HealthTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('heart_rate', 'Heart Rate'), ('blood_pressure', 'Blood Pressure'), ('temperature', 'Temperature'), ('blood_oxygen', 'Blood Oxygen'), ('respiratory_rate', 'Respiratory Rate')], max_length=20)),
                ('data', models.JSONField(default=list)),
                ('range_min', models.FloatField()),
                ('range_max', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='health_trends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conditions', models.JSONField(default=list)),
                ('allergies', models.JSONField(default=list)),
                ('surgeries', models.JSONField(default=list)),
                ('medications', models.JSONField(default=list)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.FloatField()),
                ('heart_rate_status', models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Normal', max_length=10)),
                ('blood_pressure_systolic', models.FloatField()),
                ('blood_pressure_diastolic', models.FloatField()),
                ('blood_pressure_status', models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Normal', max_length=10)),
                ('temperature', models.FloatField()),
                ('temperature_status', models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Normal', max_length=10)),
                ('blood_oxygen', models.FloatField()),
                ('blood_oxygen_status', models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Normal', max_length=10)),
                ('respiratory_rate', models.FloatField()),
                ('respiratory_rate_status', models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Normal', max_length=10)),
                ('consciousness_value', models.IntegerField()),
                ('consciousness_status', models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Normal', max_length=10)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
