# Generated by Django 5.1.6 on 2025-02-22 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitalsigns',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Vital Signs'},
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='allergies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='conditions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='medications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient',
            field=models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='surgeries',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
