# Generated by Django 5.1.6 on 2025-02-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0002_alter_vitalsigns_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthmetrics',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Health Metrics'},
        ),
        migrations.AlterModelOptions(
            name='healthtrend',
            options={'verbose_name_plural': 'Health Trends'},
        ),
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'verbose_name_plural': 'Medical History'},
        ),
    ]
