# Generated by Django 5.1.6 on 2025-02-21 16:30

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'patient'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='battery_level',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='calibration_accuracy',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='calibration_status',
            field=models.CharField(choices=[('Calibrated', 'Calibrated'), ('Needs Calibration', 'Needs Calibration'), ('In Progress', 'In Progress')], default='Needs Calibration', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='firmware_last_update',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=10, max_length=20, prefix='217', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_calibrated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_maintenance',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='next_calibration',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='next_maintenance',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='signal_strength',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicemaintenance',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='devicemaintenance',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicemaintenance',
            name='technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicemaintenance',
            name='type',
            field=models.CharField(choices=[('Calibration', 'Calibration'), ('Battery Replacement', 'Battery Replacement'), ('Firmware Update', 'Firmware Update'), ('Hardware Check', 'Hardware Check')], default='Hardware Check', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='sample_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='sensitivity',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='threshold',
            field=models.FloatField(default=0.5),
        ),
    ]
