# Generated by Django 5.1.6 on 2025-02-21 17:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-status', 'type']},
        ),
        migrations.AlterModelOptions(
            name='devicemaintenance',
            options={'ordering': ['-scheduled_for']},
        ),
        migrations.AlterModelOptions(
            name='devicereading',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='devicesettings',
            options={'ordering': ['device']},
        ),
        migrations.AlterField(
            model_name='devicemaintenance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
