# Generated by Django 5.1.6 on 2025-02-22 13:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_options_alter_devicemaintenance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereading',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
