# Generated by Django 5.1.6 on 2025-02-21 15:17

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=10, max_length=20, prefix='', primary_key=True, serialize=False, unique=True, verbose_name='User ID'),
        ),
    ]
